#!/usr/bin/env python
# coding:utf-8

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time
import sys
import unicodedata as uni
import os


def is_japanese(q):
    for char in q:
        if ('HIRAGANA' in uni.name(char)) or ('KATAKANA' in uni.name(char)) or ('CJK UNIFIED' in uni.name(char)):
            return True
    return False


def translate(q):
    if is_japanese(q):
        url = 'https://translate.google.co.jp/?hl=ja&tab=TT#ja/en/'
    else:
        url = 'https://translate.google.co.jp/?hl=ja&tab=TT#en/ja/'

    opts = Options()
    opts.add_argument('--headless')
    opts.add_argument('--disable-gpu')
    opts.add_argument('--no-sandbox')

    driver = webdriver.Chrome(chrome_options=opts)
    driver.get(url)
    input_form = driver.find_element_by_id('source')
    input_form.send_keys(q)
    time.sleep(1)
    result_form = driver.find_elements_by_id('result_box')
    result = ''
    for i in result_form:
        if i.text:
            result = i.text
            break
    driver.quit()
    return result


if __name__ == '__main__':
    print(translate(' '.join(sys.argv[1:])))
