#!/usr/bin/env python3
# coding:utf-8

import sys
import unicodedata as uni
from googletrans import Translator

def is_japanese(q):
    for char in q:
        if ('HIRAGANA' in uni.name(char)) or ('KATAKANA' in uni.name(char)) or ('CJK UNIFIED' in uni.name(char)):
            return True
    return False


def translate(q):
    if is_japanese(q):
        src = 'ja'
        dest = 'en'
    else:
        src = 'en'
        dest = 'ja'

    translator = Translator()
    result = translator.translate(q, src=src, dest=dest)

    return result.text


if __name__ == '__main__':
    print(translate(' '.join(sys.argv[1:])))
